# Generated by Django 4.1.4 on 2022-12-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table=None,
        ),
    ]
